---
version: '2'
services:
  mbtilesserver:
    build: https://github.com/DRIVER-EU/test-bed-mbtiles-service.git
    hostname: mbtilesserver
    ports:
      - "3344:3344"
    volumes:
      - ./mbtiles/:/src/mbtiles/
    environment:
      MBTILES_PORT: '3344'
